BlogCK/Areas/Admin/Controllers/AuthController.cs
using BlogCK.Entity.DTOs.Users;
using BlogCK.Entity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BlogCK.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;
        private readonly RoleManager<AppRole> roleManager;

        public AuthController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<AppRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(UserRegisterDto userRegisterDto)
        {
            if (ModelState.IsValid)
            {
                if (!userRegisterDto.AgreeToTerms)
                {
                    ModelState.AddModelError(nameof(userRegisterDto.AgreeToTerms), "You must agree to the terms and privacy policy.");
                    return View(userRegisterDto);
                }

                var user = new AppUser
                {
                    UserName = userRegisterDto.Email,
                    Email = userRegisterDto.Email,
                    FirstName="N/A",
                    LastName="N/A",
                    ImageId=Guid.Parse("07befd42-fb64-4c3f-a895-ace440aaa648")
                };

                var result = await userManager.CreateAsync(user, userRegisterDto.Password);

                if (result.Succeeded)
                {
                    var defaultRole = "User";
                    await userManager.AddToRoleAsync(user, defaultRole);

                    await signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home", new { Area = "" });
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

            }
            return View(userRegisterDto);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginDto userLoginDto)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByEmailAsync(userLoginDto.Email);
                if (user != null)
                {
                    var result = await signInManager.PasswordSignInAsync(user, userLoginDto.Password, userLoginDto.RememberMe, false);
                    if (result.Succeeded)
                    {
                        var roles=await userManager.GetRolesAsync(user);

                        if (roles.Contains("User"))
                        {
                            return RedirectToAction("Index", "Home", new { Area = "" });
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home", new { Area = "Admin" });
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Your email or password is incorrect");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Your email or password is incorrect");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        [Authorize] //kiminse logout ola bilmese ucun evvelce hemin sisteme authorize olmus olmasi lazimdi
        public async Task<IActionResult> LogOut()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home", new { Area = "" });
        }

        [HttpGet]
        [Authorize] //kiminse logout ola bilmese ucun evvelce hemin sisteme authorize olmus olmasi lazimdi
        public async Task<IActionResult> AccessDenied()
        {
            return View();
        }

    }
}

BlogCK/Areas/Admin/Views/Shared/Components/DashboardHeader/Default.cshtml
@model UserDto

<li class="nav-item navbar-dropdown dropdown-user dropdown">
    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
        <div class="avatar avatar-online">
            <img src="~/images/@Model.Image.FileName" class="rounded-circle" style="object-fit: cover; object-position: 100% 0;" />
        </div>
    </a>
    <ul class="dropdown-menu dropdown-menu-end">
        <li>
            <a class="dropdown-item" href="#">
                <div class="d-flex">
                    <div class="flex-shrink-0 me-3">
                        <div class="avatar avatar-online">
                            <img src="~/images/@Model.Image.FileName" class="rounded-circle" style="object-fit: cover; object-position: 100% 0;" />
                        </div>
                    </div>
                    <div class="flex-grow-1">
                        <span class="fw-semibold d-block">@Model.FirstName @Model.LastName</span>
                        <small class="text-muted">@Model.Role</small>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <div class="dropdown-divider"></div>
        </li>
        <li>
            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Profile">
                <i class="bx bx-user me-2"></i>
                <span class="align-middle">My Profile</span>
            </a>
        </li>
        <li>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">
                <span class="d-flex align-items-center align-middle">
                    <i class="flex-shrink-0 bx bx-arrow-back me-2"></i>
                    <span class="flex-grow-1 align-middle">Back to website</span>
                </span>
            </a>
        </li>
        <li>
            <div class="dropdown-divider"></div>
        </li>
        <li>
            <a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">
                <i class="bx bx-power-off me-2"></i>
                <span class="align-middle">Log Out</span>
            </a>
        </li>
    </ul>
</li>