BlogCK/Areas/Admin/Controllers/HomeController.cs
using BlogCK.Entity.Entities;
using BlogCK.Service.Helpers.Images;
using BlogCK.Service.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using static BlogCK.Web.ResultMessages.Messages;

namespace BlogCK.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin, Superadmin")]
    public class HomeController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly IDashboardService dashboardService;

        public HomeController(UserManager<AppUser> userManager, IDashboardService dashboardService)
        {
            this.userManager = userManager;
            this.dashboardService = dashboardService;
        }

        public async Task<IActionResult> Index()
        {
            var loggedInUser= await userManager.GetUserAsync(User);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> MontlyArticlesCount()
        {
            var count = await dashboardService.GetMontlyArticleCount();
            return Json(JsonConvert.SerializeObject(count)); 
        }

        [HttpGet]
        public async Task<IActionResult> TotalArticleCount()
        {
            var count = await dashboardService.GetTotalArticleCount();
            return Json(count);
        }
        
        [HttpGet]
        public async Task<IActionResult> TotalCategoryCount()
        {
            var count = await dashboardService.GetTotalCategoryCount();
            return Json(count);
        }
    }
}

BlogCK/Controllers/HomeController.cs
using BlogCK.Data.UnitOfWorks;
using BlogCK.Entity.Entities;
using BlogCK.Models;
using BlogCK.Service.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogCK.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        private readonly IArticleService articleService;

        public HomeController(IArticleService articleService)
        {
            //_logger = logger;
            this.articleService = articleService;
        }

        public async Task<IActionResult> Index(Guid? categoryId, int currentPage = 1, int pageSize = 3, bool isAscending = false)
        {
            var articles = await articleService.GetAllArticlesByPaging(categoryId, currentPage, pageSize, isAscending);
            return View(articles);
        }

        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 3, bool isAscending = false)
        {
            var articles = await articleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
            return View(articles);
        }

        public async Task<IActionResult> Detail(Guid articleId)
        {
            var result=await articleService.TriggerViewCount(articleId);

            return View(result);
        }



        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

BlogCK/ViewComponents/HomeCategoriesViewComponent.cs
using BlogCK.Service.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace BlogCK.Web.ViewComponents
{
    public class HomeCategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HomeCategoriesViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await categoryService.GetAllCategoriesNonDeletedAsyncTake10();

            return View(categories);
        }
    }
}

BlogCK/ViewComponents/RecentPostsViewComponent.cs
using BlogCK.Service.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace BlogCK.Web.ViewComponents
{
    public class RecentPostsViewComponent : ViewComponent
    {
        private readonly IArticleService articleService;

        public RecentPostsViewComponent(IArticleService articleService)
        {
            this.articleService = articleService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var articles = await articleService.Get3RecentArticlesWithCategoryNonDeletedAsync();

            return View(articles);
        }
    }
}

BlogCK/Views/Home/Detail.cshtml
@model ArticleDto

@{
    ViewData["Title"] = "Detail";
}

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                    <img src="~/images/@Model.Image.FileName" alt="">
                                    </div>
                                    <div class="down-content">
                                        <a href="#"><h4>@Model.Title</h4></a>
                                        <ul class="post-info">
                                            <li class="gray-text">@Model.User.FirstName @Model.User.LastName</li>
                                            <li class="gray-text">@Model.CreatedDate.ToString("dd-MMM-yyyy")</li>
                                            <li class="gray-text"><i class="fa-solid fa-eye"></i> @Model.ViewCount</li>
                                        </ul>
                                        <p> 
                                            @Model.Content
                                        </p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li>@Model.Category.Name</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        @await Component.InvokeAsync("RecentPosts")
                        @await Component.InvokeAsync("HomeCategories")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BlogCK/Views/Home/Index.cshtml
@model ArticleListDto
@{
    ViewData["Title"] = "Home Page";
}

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        @foreach (var article in Model.Articles)
                        {
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="~/images/@article.Image.FileName" alt="">
                                    </div>
                                    <div class="down-content">
                                        <a asp-controller="Home" asp-action="Detail" asp-route-aricleId="@article.Id"><h4>@article.Title</h4></a>
                                        <ul class="post-info">
                                            <li class="gray-text">@article.User.FirstName @article.User.LastName</li>
                                            <li class="gray-text">@article.CreatedDate.ToString("dd-MMM-yyyy")</li>
                                            <li class="gray-text"><i class="fa-solid fa-eye"></i> @article.ViewCount</li>
                                        </ul>
                                        <p> @(article.Content.Length > 300 ? article.Content.Substring(0, 300) : article.Content)..</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li>@article.Category.Name</li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-link"></i></li>
                                                        <li><a asp-controller="Home" asp-action="Detail" asp-route-articleId="@article.Id">Read More</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="col-lg-12">
                            <ul class="pagination justify-content-center mx-4">
                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage-1)" asp-route-pageSize="3">Previous</a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="3">@i</a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage+1)" asp-route-pageSize="3">Next</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form method="GET" asp-controller="Home" asp-action="Search">
                                    <input type="text" name="keyword" class="searchText" placeholder="type to search..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        @await Component.InvokeAsync("RecentPosts")
                        @await Component.InvokeAsync("HomeCategories")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BlogCK/Views/Home/Search.cshtml
@model ArticleListDto
@{
    ViewData["Title"] = "Home Page";
}

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        @foreach (var article in Model.Articles)
                        {
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="~/images/@article.Image.FileName" alt="">
                                    </div>
                                    <div class="down-content">
                                        <a asp-controller="Home" asp-action="Detail" asp-route-aricleId="@article.Id"><h4>@article.Title</h4></a>
                                        <ul class="post-info">
                                            <li class="gray-text">@article.User.FirstName @article.User.LastName</li>
                                            <li class="gray-text">@article.CreatedDate.ToString("dd-MMM-yyyy")</li>
                                            <li class="gray-text"><i class="fa-solid fa-eye"></i> @article.ViewCount</li>
                                        </ul>
                                        <p> @(article.Content.Length > 300 ? article.Content.Substring(0, 300) : article.Content)..</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li>@article.Category.Name</li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-link"></i></li>
                                                        <li><a asp-controller="Home" asp-action="Detail" asp-route-articleId="@article.Id">Read More</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="col-lg-12">
                            <ul class="pagination justify-content-center mx-4">
                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage-1)" asp-route-pageSize="3">Previous</a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="3">@i</a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage+1)" asp-route-pageSize="3">Next</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form method="GET" asp-controller="Home" asp-action="Search">
                                    <input type="text" name="keyword" class="searchText" placeholder="type to search..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        @await Component.InvokeAsync("RecentPosts")
                        @await Component.InvokeAsync("HomeCategories")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>